# Generated by Django 5.2.7 on 2025-10-05 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True)),
                ('piso', models.IntegerField()),
                ('tipo', models.CharField(max_length=50)),
                ('capacidad', models.IntegerField()),
                ('estado', models.CharField(default='activa', max_length=20)),
                ('frigobar', models.BooleanField(default=False)),
                ('jacuzzi', models.BooleanField(default=False)),
                ('balcon', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
            options={
                'db_table': 'HABITACION',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('doc_tipo', models.CharField(blank=True, max_length=20, null=True)),
                ('doc_num', models.CharField(blank=True, max_length=50, null=True)),
                ('tel', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
            options={
                'db_table': 'PERSONA',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_checkin', models.DateField()),
                ('fecha_checkout', models.DateField()),
                ('estado', models.CharField(default='pendiente', max_length=20)),
                ('canal', models.CharField(blank=True, max_length=50, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('titular_persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.persona')),
            ],
            options={
                'db_table': 'RESERVA',
            },
        ),
        migrations.CreateModel(
            name='ReservaHabitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habitacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='hotel.habitacion')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hotel.reserva')),
            ],
            options={
                'db_table': 'RESERVA_HABITACION',
                'unique_together': {('reserva', 'habitacion')},
            },
        ),
    ]
